<a href="https://colab.research.google.com/github/ulises1229/INTRO-PYTHON-ENESJ/blob/master/code/d%C3%ADa2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Día 2 - Almacenamiento de datos
##### Autor: Ulises Olivares
##### uolivares@unam.mx
##### 01 septiembre de 2020

#### *Numpy*

Demostrar el uso de arreglos unidimensionales y bi-dimensionales utilizando numpy.


In [ ]:
# importar librería de numpy 
import numpy as np

# Creara un arreglo bi-dimensional
a = np.array([[1,2,3], 
              [4,5,6]], 
             dtype = np.float32)
# Imprimir matriz
print(a)

# IMP
print("Dimensiones: " + str(a.ndim))
print("Forma: " + str(a.shape))
print("Tipo de datos: " + str(a.dtype))

In [ ]:
# Creación de arreglos
# Arreglo de 1s
ones = np.ones((5,5), dtype=np.float32)
# Arreglo de 0s
zeros = np.zeros((5,5), dtype=np.float32)

#Impresión de matrices
print(ones)
print(zeros)

# Acceso a la matriz usando índices
for i in range(0, len(ones)):
  for j in range(0, len(ones[0])):
    print(ones[i][j], end= " ")
  print(" ")

# Acceso usando elementos
for i in ones:
  for j in i:
    print(j , end =" ")
  print(" ")

In [ ]:
# Generación de un vector a través del uso de rangos
np.arange(1, 100)

In [43]:
# Concatenando arreglos o matrices
A = np.ones((5,3), dtype = np.float32)
B = np.zeros((5,4), dtype = np.float32)

# concatenar matrices
np.concatenate([A,B], axis = 1)

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
# Uso de Astype para hacer un cast de tipos de datos
A = np.zeros((5,4), dtype = np.float32)
print(len(A[0]))

for i in range(len(A)):
  for j in range(len(A[0])):
    A[i][j] = np.pi
print(A)

print(A.astype(np.int16))

In [74]:
# Uso de np.zeros_like y np.ones_like
A = np.ones((4,4))
print(A)
# zeros_like genera un arreglo de las 
# mismas dimensiones que el original 
B = np.zeros_like(A)
print(B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


In [83]:
# Generación de arreglos aleatorios
A = np.random.random((5, 5))
print(A)
# Generación de números enteros del 0 al n-1 
n = 10
B= np.random.randint(10, size = (7,7))
print(B)

[[0.15632288 0.73735589 0.77775127 0.77383993 0.51336574]
 [0.53877873 0.69228787 0.06430154 0.50413543 0.32967815]
 [0.4927091  0.14194562 0.8078162  0.19333272 0.49208783]
 [0.0791934  0.86787715 0.81568641 0.97690664 0.82011968]
 [0.90603684 0.64281865 0.14918772 0.15695209 0.82954009]]
[[6 7 1 8 3 3 1]
 [5 6 3 3 1 9 1]
 [5 7 9 9 7 4 6]
 [2 8 5 9 8 9 1]
 [9 5 3 5 4 4 2]
 [0 9 6 2 9 2 5]
 [6 4 8 9 4 0 8]]


In [98]:
# Transformaciones de arreglos
A = np.array([1,2,3,4,5,6])
print(A)

# Transformar a 3 filas, 2 columnas
A = A.reshape(3, 2)
print(A)

# Se utiliza -1 para determinar cols
A = A.reshape(2, -1)
print(A)

# Transormar a un arreglo lineal
A = A.ravel()
print(A)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [106]:
# Transpuesta de una matriz
A = np.arange(25).reshape(5,5)
print("Matriz Original: \n" + str(A))
# Imprimir matriz transpuesta
print("Matriz Transpuesta: \n" + str(A.T))
# Imprimir matriz 
print("Matriz Transpuesta: \n" + str(A.transpose((1,0))))



Matriz Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Matriz Transpuesta: 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
Matriz Transpuesta: 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
