<a href="https://colab.research.google.com/github/ulises1229/INTRO-PYTHON-ENESJ/blob/master/code/d%C3%ADa5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Día5 - Deep Learning con Pythorch
+ Autor: Ulises Olivares, Walter André Reyes
+ uolivares@unam.mx
+ 03 de septiembre de 2020

---
Contenido basado en la documentación oficial de Pythorch: 
- https://pytorch.org/tutorials/

---



¿Qué es Pythorch?
================

Es un paquete informático científico basado en Python dirigido a dos conjuntos de
audiencias:

- Un reemplazo de NumPy para usar el poder de cómputo de los GPU.

- Una plataforma de investigación de (deep learning) que proporciona máxima flexibilidad y velocidad

**Tensores**
---------------

+ Los tensores son similares a los ndarrays de NumPy, con la adición de que también se pueden usar en un GPU para acelerar los cálculos.



In [ ]:
# Google Colab soporta Pythorch por default
import torch


Nota
======

Se declara una matriz no inicializada, esta matriz no contiene valores definidos antes de su uso. Cuando se crea una matriz no inicializada, los valores que estaban en la memoria asignada en ese momento aparecerán como valores iniciales.



In [42]:
# Matriz no inicializada de 5 filas y 3 columnas
x = torch.empty(5, 3)
print(x)

tensor([[1.7503e-35, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4574e-43, 1.3593e-43, 1.5975e-43],
        [1.4153e-43, 1.4013e-43, 5.6052e-44],
        [5.7453e-44, 0.0000e+00, 0.0000e+00]])


*Construir* una matriz no inicializada de 5x3:



In [ ]:
x = torch.empty(5, 3)
print(x)

Construir una matriz inicializada de forma aleatoria:



In [ ]:
x = torch.rand(5, 3)
print(x)

Construir una matriz de zeros y de tyopo long:

- Ver tipos de datos de pythorch en el siguiente [LINK](https://pytorch.org/docs/stable/tensor_attributes.html)


In [17]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**Construir un Tensor a partir de datos:**
  + Se especifican los elementos entre corchetes. E.g. [1,2,3,5]




In [18]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


**Crear un tensor basado en un tensor existente**

Este método reutilizá las propiedades del tensor de entrada. E.g. **dtype**, a menos que los nuevos valores se especifiquen por el usuario.

In [21]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # sobreescibir dtype!
print(x)                                      # el resultado tiene el mismo tamaño.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.5462, -1.4558,  3.1613],
        [-0.5051, -1.5140, -1.4744],
        [ 1.0144, -0.6478, -1.1869],
        [-1.0717, -0.0900,  0.2812],
        [-1.0053, -1.4958,  0.7683]])


**Obtener el tamaño de un tensor:**



In [ ]:
print(x.size())

<h4>Nota</h4><p>

`torch.Size`

Es de hecho una tupla, entonces soporta las operaciones de tuplas.</p></div>

**Operaciones**

Existen múltiples formas de especificar (denotar) operaciones en pythorch. En el siguiente ejemplo, se utilizara la operación de adición. 

**Suma: sintaxis 1**



In [22]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.0351, -0.7326,  4.0632],
        [ 0.1474, -0.6312, -0.5010],
        [ 1.4052,  0.0893, -1.1074],
        [-1.0232,  0.8573,  0.4827],
        [-0.8142, -0.5027,  1.3483]])


**Suma: sintaxis 2**



In [23]:
print(torch.add(x, y))

tensor([[-1.0351, -0.7326,  4.0632],
        [ 0.1474, -0.6312, -0.5010],
        [ 1.4052,  0.0893, -1.1074],
        [-1.0232,  0.8573,  0.4827],
        [-0.8142, -0.5027,  1.3483]])


**Suma: Sintaxis 3** 
- pasar la variable resultado como un argumento.

In [24]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0351, -0.7326,  4.0632],
        [ 0.1474, -0.6312, -0.5010],
        [ 1.4052,  0.0893, -1.1074],
        [-1.0232,  0.8573,  0.4827],
        [-0.8142, -0.5027,  1.3483]])


**Suma: Sintaxis 4**
- Operación in-situ


In [25]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.0351, -0.7326,  4.0632],
        [ 0.1474, -0.6312, -0.5010],
        [ 1.4052,  0.0893, -1.1074],
        [-1.0232,  0.8573,  0.4827],
        [-0.8142, -0.5027,  1.3483]])


**Nota**

Cualquier operación que modifique un tensor in-situ lleva el sufijo `_` 

Por ejemplo: 

``x.copy_(y)``, ``x.t_()``, modificarán al tensor ``x``

- **¡Es posible utilizar la notación de indexación similar a Numpy!**

In [34]:
print(x[:, 1])

tensor([ 0.3038, -0.0759,  0.8677,  0.9201])


**Modificar el tamaño:** Si es necesario modificar el tamaño o la forma de un tensoer, se puede utilizar:

``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # el tamaño -1 se asigna automáticamente (infiere) de la otra dimensión.
print(x.size(), y.size(), z.size())

Si se tiene un único elemento en el tensor, se puede emplear ``.item()`` para obtener el valor como un número de Python.

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

**Revisar más tarde:**

  - Más de 100 operaciones con tensores incluidos:
    + Transposiciones
    + Indexación
    + Subconjuntos
    + Operaciones matemáticas
    + Operaciones de álgebra lineal
    + Números aleatorios, etc

Todas estas operaciones están descritas
  `aquí <https://pytorch.org/docs/torch>`_.

Conversión de Torch Tensor a Numpy Array y viceversa
---

La conversión es muy sencilla

El arraglo de Numpy y el Tensor compartirán la ubicación de memoria subyacente
(si el tensor de Torch está en el CPU), cambiar un elemento modificará atomáticamente el otro.

**Convirtiendo un Tensor Torch a un Numpy Array**

In [39]:
# Torch tensor
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
# Arreglo de numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]



Verificar el arraglo de numpy.


In [ ]:
a.add_(1)
print(a)
print(b)

Convirtiendo el arreglo de Numpy a un Tensor Torch
---
See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!