<a href="https://colab.research.google.com/github/ulises1229/INTRO-PYTHON-ENESJ/blob/master/code/d%C3%ADa2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Día 2 - Almacenamiento de datos
##### Autor: Ulises Olivares
##### uolivares@unam.mx
##### 01 septiembre de 2020

#### Numpy

In [13]:
# importar librería de numpy 
import numpy as np

# Creara un arreglo bi-dimensional
a = np.array([[1,2,3], 
              [4,5,6]], 
             dtype = np.float32)
# Imprimir matriz
print(a)

# IMP
print("Dimensiones: " + str(a.ndim))
print("Forma: " + str(a.shape))
print("Tipo de datos: " + str(a.dtype))

[[1. 2. 3.]
 [4. 5. 6.]]
Dimensiones: 2
Forma: (2, 3)
Tipo de datos: float32


In [27]:
# Creación de arreglos
# Arreglo de 1s
ones = np.ones((5,5), dtype=np.float32)
# Arreglo de 0s
zeros = np.zeros((5,5), dtype=np.float32)

#Impresión de matrices
print(ones)
print(zeros)

# Acceso a la matriz usando índices
for i in range(0, len(ones)):
  for j in range(0, len(ones[0])):
    print(ones[i][j], end= " ")
  print(" ")

# Acceso usando elementos
for i in ones:
  for j in i:
    print(j , end =" ")
  print(" ")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  


In [ ]:
np.arange